# Generated by Django 5.2.4 on 2025-08-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='faculty_pics/', verbose_name='Photo')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, help_text='Experience in years', null=True)),
            ],
        ),
    ]
