name = input("Enter Your Name:-")
cls = input("Enter Your Class:-")
print("Hello, Students please Enter your Exam Marks out of 100/ :-")
h = int (input("Enter Your Hindi Marks 100/:-"))
e =int (input("Enter Your English Marks 100/:-"))
m= int(input("Enter Your Maths Marks 100/:-"))
p = int(input("Enter Your Physics Marks 100/:-"))
c = int(input("Enter Your Chemastry Marks 100/:-"))
sum = (h+e+m+p+c)
per = sum/5
print("Totle:-",sum)
print("your hindi marks 100/:-",h)
print("your englisg marks 100/ :-",e)
print("your maths marks 100/:-",m)
print("your physics marks 100/:-",p)
print("your chemastry marks 100/:-",c)
print("Percentage:-",per)
print("THANK YOU")