# Generated by Django 5.2.4 on 2025-08-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studentregistration_teacherregistration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerRegistration',
        ),
    ]
