# Generated by Django 5.2.4 on 2025-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_workerregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=100)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
