# Generated by Django 5.2.4 on 2025-08-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_workerregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='mobile_number',
            field=models.CharField(default=987654321, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='mobile_number',
            field=models.CharField(default=987654321, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerregistration',
            name='mobile_number',
            field=models.CharField(default=987654321, max_length=15),
            preserve_default=False,
        ),
    ]
