# Generated by Django 5.2.4 on 2025-08-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_studentregistration_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Photo'),
        ),
    ]
