# Generated by Django 5.2.4 on 2025-08-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_faculty_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty',
            new_name='Teacher',
        ),
    ]
