# Generated by Django 5.2.4 on 2025-08-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_faculty_to_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherRegistration',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_id',
            field=models.CharField(default='xyz', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
