# Generated by Django 5.2.4 on 2025-08-28 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_teacherregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
