# Generated by Django 5.2.4 on 2025-08-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_teacher_age_alter_teacher_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(default='ram', max_length=100),
            preserve_default=False,
        ),
    ]
