# Generated by Django 5.2.4 on 2025-09-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='class_name',
            field=models.CharField(default='6th', max_length=100),
            preserve_default=False,
        ),
    ]
